name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Parspack server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          # port: ${{secrets.PORT}}
          script: |
            cd /var/www/quantum
            git reset --hard
            git checkout main
            git pull
            chmod -R 777 storage/logs/*
